### ISSUE TITLE
Netmirror repo

### ISSUE THREAD

**Issue by KotlinJS5** [flixclusiveorg/provider-docs#1]
There's a website called iosmirror.cc that provides Netflix and Amazon content (almost everything, from recent to old). A repo for Cloudstream is already available, but since I’m a big fan of Flixclusive, I’d love to have it there if possible. If someone could make that happen, it would be amazing for me.

Thank you!
Netmirror dot app

**Comment by rhenwinch** [comment]
unrelated issue for the docs repository, closing as not planned.
